---

- hosts: smartnic
  remote_user: root
  roles:
    - ../roles/disconnect_bridge_external
    - ../roles/teardown_ovs_bridge
    - ../roles/stop_ovs
    - ../roles/setup_pairs
    - ../roles/setup_linux_bridge
