---

- name: Setup OVS bridge
  block:
    - name: Create bridge with DPDK datapath
      openvswitch_bridge:
        bridge: ovs-br0
        state: present
        set: bridge ovs-br0 datapath_type=netdev

    - name: Assign IP to bridge
      command:
        cmd: ip addr add {{bridge_ip}}/24 dev ovs-br0

    - name: Bring up bridge
      command:
        cmd: ip link set dev ovs-br0 up

    - name: add PF4 aka int0
      openvswitch_port:
        bridge: ovs-br0
        port: int0
        state: present
        set: Interface int0 type=dpdk options:dpdk-devargs=0008:01:00.4 ofport_request=1 options:n_rxq=1

    - name: add PF5 aka int1
      openvswitch_port:
        bridge: ovs-br0
        port: int1
        state: present
        set: Interface int1 type=dpdk options:dpdk-devargs=0008:01:00.5 ofport_request=2 options:n_rxq=1

    - name: add PF0 aka ext0
      openvswitch_port:
        bridge: ovs-br0
        port: ext0
        state: present
        set: Interface ext0 type=dpdk options:dpdk-devargs=0008:01:00.0 ofport_request=3 options:n_rxq=1

    - name: add PF1 aka ext1
      openvswitch_port:
        bridge: ovs-br0
        port: ext1
        state: present
        set: Interface ext1 type=dpdk options:dpdk-devargs=0008:01:00.1 ofport_request=4 options:n_rxq=1

    - name: Record OVS bridge active
      set_fact:
        ovs_bridge_active: true
        cacheable: yes
  when: ovs_bridge_active is undefined or not ovs_bridge_active
